//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Branding {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Branding() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Common.Branding", typeof(Branding).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loss Factor.
        /// </summary>
        internal static string StrUnitLfLong {
            get {
                return ResourceManager.GetString("StrUnitLfLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to %LF.
        /// </summary>
        internal static string StrUnitLfShort {
            get {
                return ResourceManager.GetString("StrUnitLfShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oil Quality Index.
        /// </summary>
        internal static string StrUnitOqiLong {
            get {
                return ResourceManager.GetString("StrUnitOqiLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OQI.
        /// </summary>
        internal static string StrUnitOqiShort {
            get {
                return ResourceManager.GetString("StrUnitOqiShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tan Delta Number.
        /// </summary>
        internal static string StrUnitTdnLong {
            get {
                return ResourceManager.GetString("StrUnitTdnLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TDN.
        /// </summary>
        internal static string StrUnitTdnShort {
            get {
                return ResourceManager.GetString("StrUnitTdnShort", resourceCulture);
            }
        }
    }
}
